# Generated by Django 3.1.2 on 2021-03-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestRewardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(max_length=100)),
                ('target_time', models.IntegerField()),
            ],
            options={
                'db_table': 'QuestReward',
            },
        ),
        migrations.CreateModel(
            name='StudyTimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_time', models.IntegerField()),
            ],
            options={
                'db_table': 'StudyTime',
            },
        ),
    ]
